name: pixel_scan_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cunning_document_scanner: ^1.2.3
  pro_image_editor: ^8.2.0
  purchases_flutter: ^8.10.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.1.0
  url_launcher: ^6.2.0
  path_provider: ^2.1.2
  pdf: ^3.10.8
  printing: ^5.12.0
  share_plus: ^10.0.3
  intl: ^0.20.2
  file_picker: ^8.0.0
  pdfx: ^2.6.0
  shadcn_ui: ^0.43.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 100